name: 'Lint Web Codebase'
description: 'Run linting'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '13.x'
        cache: yarn
        cache-dependency-path: nuxt/yarn.lock

    - name: Install Dependencies
      shell: bash
      working-directory: ./nuxt
      run: yarn install --frozen-lockfile

    - name: Lint Codebase
      shell: bash
      working-directory: ./nuxt
      run: NODE_ENV=production yarn lint --no-fix --format stylish
