name: 'Build Test API Image'
description: 'Build a Docker image for the Laravel backend'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Test Image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        tags: nawhas/api:test
        push: false
        target: test
        load: true
        cache-from: type=registry,ref=nawhas/api:buildcache
