version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env.production
    depends_on:
      - db
      - events_db
      - data_db
      - cache
      - search
  queue:
    build:
      context: api
      dockerfile: Dockerfile
    command: php artisan horizon
    env_file:
      - api/.env.production
    restart: unless-stopped
  web:
    build:
      context: nuxt
      dockerfile: Dockerfile
      args:
        APP_VERSION: local-0.0.1
    networks:
      - nawhas



