version: '3'

volumes:
  web_docker_node_modules:

services:
  api:
    image: szainmehdi/php:7.4-dev-20210813
    working_dir: /var/www/api
    environment:
      - APP_ENV=local
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./api:/var/www/api:delegated
    ports:
      - "9000:9000"
  queue:
    image: szainmehdi/php:7.4-dev-20210813
    working_dir: /var/www/api
    command: php artisan horizon
    environment:
      - APP_ENV=local
    volumes:
      - ./api:/var/www/api:delegated
  web:
    image: szainmehdi/node:13
    working_dir: /opt
    volumes:
      - ./nuxt:/opt:delegated
      - web_docker_node_modules:/opt/node_modules
    command: yarn dev:docker
    restart: unless-stopped
  dusk:
    image: selenium/standalone-chrome:latest
    container_name: nawhas_dusk
    depends_on:
      - ingress
    links:
      - "ingress:nawhas.test"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - nawhas
