version: '3.9'

services:
  api:
    image: nawhas/api:local
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env.production
  queue:
    image: nawhas/api:local
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env.production
  web:
    image: nawhas/web:local
    build:
      context: nuxt
      dockerfile: Dockerfile
      args:
        APP_ENV: development
        APP_VERSION: local-0.0.1
  # Dusk Profile
  dusk:
    image: nawhas/api-test:local
    build:
      context: api
      dockerfile: Dockerfile
      target: test
    restart: 'no'
    profiles:
      - dusk
    environment:
      - APP_ENV=test
      - APP_URL=http://nawhas.test:3000
    networks:
      - nawhas
    depends_on:
      - events_db
      - data_db
      - nginx
      - web
      - search
      - selenium
  selenium:
    profiles:
      - dusk
    image: 'selenium/standalone-chrome'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - nawhas


