version: '3.9'

services:
  api:
    image: nawhas/api:local
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env.production
  queue:
    image: nawhas/api:local
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env.production
  web:
    image: nawhas/web:local
    build:
      context: nuxt
      dockerfile: Dockerfile
      args:
        APP_ENV: development
        APP_VERSION: local-0.0.1


