version: '3.9'

services:
  api:
    image: szainmehdi/php:8.1-dev-20230802
    user: "1000:1000"
    working_dir: /var/www/api
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./api:/var/www/api:delegated
  queue:
    image: szainmehdi/php:8.1-dev-20230802
    working_dir: /var/www/api
    environment:
      - APP_ENV=local
    volumes:
      - ./api:/var/www/api:delegated
  test:
    image: szainmehdi/php:8.1-dev-20230802
    user: "1000:1000"
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api:delegated
  web:
    command: ['yarn', 'watcher']
    working_dir: /home/nawhas/web
    build:
      context: ./nuxt
      target: dev
    volumes:
      - ./nuxt:/home/nawhas/web:delegated
      - /dev/shm:/dev/shm
    environment:
      - BUILD_AXIOS_DEBUG=
      - CHOKIDAR_USEPOLLING=true
      - SERVER_API_BASE_URL=http://nginx:80
