version: '3'

networks:
  nawhas:

volumes:
  mariadb:

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: nawhas_api
    env_file:
      - api/.env.staging
    networks:
      - nawhas
    depends_on:
      - mysql
  ingress:
    image: nginx:stable-alpine
    container_name: nawhas_ingress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/ingress.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_nginx
      - web_nginx
    networks:
      - nawhas
  api_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        FPM_CONTAINER: nawhas_api
    container_name: nawhas_api_nginx
    depends_on:
      - api
      - mysql
    networks:
      - nawhas
  web_nginx:
    image: nginx:stable-alpine
    container_name: nawhas_web_nginx
    working_dir: /var/www/web/public
    volumes:
      - ./web/dist:/var/www/web/public
      - ./docker/nginx/web.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nawhas
  mysql:
    image: mariadb:10
    container_name: nawhas_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nawhas
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - nawhas



