version: '3.9'

networks:
  nawhas:

volumes:
  db:
  redis:
  search:

services:
  api:
    platform: linux/amd64
    networks:
      - nawhas
    depends_on:
      - db
      - cache
  queue:
    platform: linux/amd64
    networks:
      - nawhas
    restart: unless-stopped
    command: php artisan horizon
    depends_on:
      - db
      - cache
  test:
    platform: linux/amd64
    profiles:
      - test
    restart: 'no'
    environment:
      - APP_ENV=testing
      - APP_URL=https://nawhas.test
      # Uncomment this line to enable debugging dusk tests visually.
      # - DUSK_HEADLESS_DISABLED=true
    depends_on:
      - search
      - db
    networks:
      - nawhas
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nawhas
    depends_on:
      - api
  ingress:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/ingress.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nginx
      - web
    networks:
      nawhas:
        aliases:
          - nawhas.test
          - api.nawhas.test
  web:
    platform: linux/amd64
    expose:
      - 3000
    environment:
      - BUILD_APP_ENV=development
      - API_BASE_URL=https://api.nawhas.test/
      - SERVER_API_BASE_URL=http://api.nawhas.test/
      - SEARCH_HOST=https://search.nawhas.test
      - APP_DOMAIN=https://nawhas.test
      - HOST=0.0.0.0
    networks:
      - nawhas
  db:
    image: postgres:11
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=nawhas_data,nawhas_events,nawhas_data_test,nawhas_events_test
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data:delegated
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - nawhas
  cache:
    image: redis:5
    networks:
      - nawhas
    volumes:
      - redis:/data
  search:
    image: getmeili/meilisearch:v0.24.0
    restart: unless-stopped
    tty: true
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=secret
    volumes:
      - search:/data.ms:delegated
    networks:
      - nawhas
  mail:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - nawhas
  selenium:
    profiles:
      - dusk
    image: 'selenium/standalone-chrome'
    # Uncomment the following lines for visaul debugging dusk tests.
#    image: 'selenium/standalone-chrome-debug'
#    ports:
#      - '5900:5900'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - nawhas
