version: '3.9'

services:
  api:
    image: nawhas/api:${API_IMAGE_TAG}
    environment:
      - APP_ENV=testing
  queue:
    image: nawhas/api:${API_IMAGE_TAG}
    environment:
      - APP_ENV=testing
  web:
    image: nawhas/web:${WEB_IMAGE_TAG}
  test:
    image: nawhas/api:${API_TEST_IMAGE_TAG}
    environment:
      - APP_ENV=testing
    volumes:
      - ./api/tests/Browser/screenshots:/var/www/api/tests/Browser/screenshots
      - ./api/tests/Browser/console:/var/www/api/tests/Browser/console

