version: '3.9'

networks:
  nawhas:

volumes:
  postgres:
  pg_events:
  pg_data:
  redis:
  search:
  web_node_modules:
  web_nuxt_built:

services:
  api:
    image: szainmehdi/php:7.4-dev-20210813
    working_dir: /var/www/api
    environment:
      - APP_ENV=local
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./api:/var/www/api:delegated
    ports:
      - "9000:9000"
    networks:
      nawhas:
        aliases:
          - api-fpm
    depends_on:
      - db
      - events_db
      - data_db
      - cache
  queue:
    image: szainmehdi/php:7.4-dev-20210813
    working_dir: /var/www/api
    environment:
      - APP_ENV=local
    volumes:
      - ./api:/var/www/api:delegated
    networks:
      - nawhas
    restart: unless-stopped
    command: php artisan horizon
    depends_on:
      - db
      - events_db
      - data_db
      - cache
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      nawhas:
        aliases:
          - api.nawhas.test
          - api-nginx
          - nawhas_api_nginx
    depends_on:
      - api
  ingress:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/ingress.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nginx
      - web
    networks:
      - nawhas
  # This container just exists to keep make the ingress continue to work.
  web:
    command: ['yarn', 'watcher']
    working_dir: /opt
    image: szainmehdi/node:13
    expose:
      - 3000
    volumes:
      - ./nuxt:/opt:delegated
      - web_node_modules:/opt/node_modules
      - web_nuxt_built:/opt/.nuxt
    environment:
      - HOST=0.0.0.0
      - APP_ENV=test
      - CHOKIDAR_USEPOLLING=true
      - SERVER_API_BASE_URL=http://api.nawhas.test
    networks:
      nawhas:
        aliases:
          - nawhas.test
          - nawhas_web
  db:
    image: postgres:11
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
      - ./docker/postgres/scripts:/usr/local/sbin
    networks:
      nawhas:
        aliases:
          - nawhas_db
  events_db:
    image: postgres:11
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nawhas_events
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_events:/var/lib/postgresql/data:delegated
    networks:
      nawhas:
        aliases:
          - nawhas_events_db
  data_db:
    image: postgres:11
    restart: unless-stopped
    tty: true
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=nawhas_data
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_data:/var/lib/postgresql/data:delegated
    networks:
      nawhas:
        aliases:
          - nawhas_data_db
  cache:
    image: redis:5
    networks:
      - nawhas
    volumes:
      - redis:/data
  search:
    image: getmeili/meilisearch:v0.13.0
    restart: unless-stopped
    tty: true
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=secret
    volumes:
      - search:/data.ms:delegated
    networks:
      nawhas:
        aliases:
          - search
          - nawhas_search
  mail:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      nawhas:
        aliases:
          - mail
  # Dusk Profile
  dusk:
    image: szainmehdi/php:7.4-dev-20210813
    working_dir: /var/www/api
    restart: 'no'
    profiles:
      - dusk
    environment:
      - APP_ENV=test
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - APP_URL=http://nawhas.test:3000
    volumes:
      - ./api:/var/www/api:delegated
    networks:
      - nawhas
    depends_on:
      - db
      - events_db
      - data_db
      - nginx
      - web
      - search
      - selenium
  selenium:
    profiles:
      - dusk
    image: 'selenium/standalone-chrome'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - nawhas
