version: '3'

networks:
  nawhas:

volumes:
  postgres:
  pg_events:
  pg_data:
  redis:
  search:

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: nawhas_api
    env_file:
      - api/.env.production
    networks:
      - nawhas
    depends_on:
      - db
      - events_db
      - data_db
      - cache
      - search
  queue:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: nawhas_queue
    env_file:
      - api/.env.production
    networks:
      - nawhas
    restart: unless-stopped
    command: php artisan horizon
    depends_on:
      - api
  nginx:
    image: nginx:stable-alpine
    container_name: nawhas_api_nginx
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nawhas
    depends_on:
      - api
  ingress:
    image: nginx:stable-alpine
    container_name: nawhas_ingress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/ingress.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - nginx
    networks:
      - nawhas
  web:
    build:
      context: nuxt
      dockerfile: Dockerfile
      args:
        SENTRY_PUBLISH_RELEASE: 1
        APP_VERSION: local-0.0.1
    container_name: nawhas_web
    networks:
      - nawhas
  db:
    image: postgres:11
    container_name: nawhas_db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nawhas
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nawhas
  events_db:
    image: postgres:11
    container_name: nawhas_events_db
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nawhas_events
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_events:/var/lib/postgresql/data
    networks:
      - nawhas
  data_db:
    image: postgres:11
    container_name: nawhas_data_db
    restart: unless-stopped
    tty: true
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=nawhas_data
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nawhas
  cache:
    image: redis:5
    container_name: nawhas_cache
    networks:
      - nawhas
    volumes:
      - redis:/data
  search:
    image: getmeili/meilisearch:v0.13.0
    container_name: nawhas_search
    restart: unless-stopped
    tty: true
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=secret
    volumes:
      - search:/data.ms
    networks:
      - nawhas



