version: '3.9'

services:
  api:
    image: nawhas/api:local
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
  queue:
    image: nawhas/api:local
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
  test:
    image: szainmehdi/php:8.1-dev-20211203
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api:delegated
  web:
    image: nawhas/web:local
    build:
      context: nuxt
      dockerfile: Dockerfile
      args:
        APP_ENV: development
        APP_VERSION: local-0.0.1


