version: '3'

networks:
  nawhas:

volumes:
  mariadb:

services:
  api:
    image: szainmehdi/php:7.4-dev
    working_dir: /var/www/api
    environment:
      - XDEBUG_ENABLE=true
      - XDEBUG_REMOTE_PORT=9001
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_REMOTE_HOST=host.docker.internal
    volumes:
      - ./api:/var/www/api
    ports:
      - "9000:9000"



