version: '3'

networks:
  nawhas:

volumes:
  postgres:
  pg_events:
  pg_data:
  redis:
  search:

services:
  api:
    image: szainmehdi/php:7.4-dev
    container_name: nawhas_api
    working_dir: /var/www/api
    environment:
      - APP_ENV=local
      - XDEBUG_ENABLE=true
      - XDEBUG_REMOTE_PORT=9001
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_REMOTE_HOST=host.docker.internal
    volumes:
      - ./api:/var/www/api:cached
    ports:
      - "9000:9000"
    networks:
      - nawhas
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    container_name: nawhas_api_nginx
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nawhas
    depends_on:
      - api
  ingress:
    image: nginx:stable-alpine
    container_name: nawhas_ingress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/ingress.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nginx
      - web
    networks:
      - nawhas
  web:
    image: nginx:stable-alpine
    container_name: nawhas_web
    working_dir: /var/www/web/public
    volumes:
      - ./web/dist:/var/www/web/public
      - ./web/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nawhas
  db:
    image: postgres:11
    container_name: nawhas_db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/scripts:/usr/local/sbin
    networks:
      - nawhas
  events_db:
    image: postgres:11
    container_name: nawhas_events_db
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nawhas_events
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_events:/var/lib/postgresql/data
    networks:
      - nawhas
  data_db:
    image: postgres:11
    container_name: nawhas_data_db
    restart: unless-stopped
    tty: true
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=nawhas_data
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nawhas
  cache:
    image: redis:5
    container_name: nawhas_cache
    networks:
      - nawhas
    volumes:
      - redis:/data
  search:
    image: getmeili/meilisearch:v0.12.0
    container_name: nawhas_search
    restart: unless-stopped
    tty: true
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=secret
    volumes:
      - search:/data.ms
    networks:
      - nawhas
