services:
  # Staging: Vue Frontend App
  - type: web
    name: Nawhas.com Staging - Web
    env: static
    buildCommand: cd web && yarn build
    staticPublishPath: ./web/dist
    pullRequestPreviewsEnabled: false
    domains:
      - staging.nawhas.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VUE_APP_API_DOMAIN
        value: https://api.staging.nawhas.com

