name: 'Build API Image'
description: 'Build a Docker image for the Laravel backend'
inputs:
  docker-username:
    description: 'Docker username'
    required: true
  docker-password:
    description: 'Docker password'
    required: true
  extra-tags:
    description: 'Additional tags (e.g. nawhas/api:staging)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Prepare Environment Variables
      id: environment
      shell: bash
      run: |
        version="dev-${SHA::8}"
        echo "::set-output name=version::${version}"
        echo "Version: ${version}"
      env:
        SHA: ${{ github.sha }}
        EVENT_PATH: ${{ github.event_path }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build Test Image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        tags: |
          nawhas/api:test
        push: false
        target: test
        load: true
        cache-from: type=registry,ref=nawhas/api:buildcache
        cache-to: type=registry,ref=nawhas/api:buildcache,mode=max

    - name: Run Psalm
      shell: bash
      run: |
        docker run --rm nawhas/api:test ./docker/scripts/psalm.sh

    - name: Build Production Image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        build-args: |
          GITHUB_SHA=${{ github.sha }}
        tags: |
          nawhas/api:${{ steps.environment.outputs.version }}
          ${{ inputs.extra-tags }}
        push: true
        cache-from: type=registry,ref=nawhas/api:buildcache
        cache-to: type=registry,ref=nawhas/api:buildcache,mode=max
