apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    tier: backend
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        tier: backend
    spec:
      containers:
      - name: {{ .Values.api.containerName }}
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        imagePullPolicy: IfNotPresent
        env:
          {{- range $key, $value := .Values.api.apiEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
        livenessProbe:
          exec:
            command:
            - php
            - artisan
            - healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - php
            - artisan
            - healthcheck
          initialDelaySeconds: 2
          timeoutSeconds: 2
