apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  labels:
    app: {{ .Values.web.name }}
    tier: frontend
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
        tier: frontend
    spec:
      containers:
        - name: {{ .Values.web.containerName }}
          image: {{ .Values.web.image }}:{{ .Values.web.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000