kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.web.name }}
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    app: {{ .Values.web.name }}
    tier: frontend
  ports:
    - name: 'nuxt'
      port: 3000
      targetPort: 3000
      protocol: TCP
