apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: {{ .Values.cache.name }}
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: {{ .Values.cache.name }}
    role: master
    tier: backend
