kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.apiNginx.name }}
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: {{ .Values.apiNginx.name }}
    tier: backend
  ports:
    - name: 'nginx'
      port: 80
      targetPort: 80
      protocol: TCP