kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.search.name }}
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: {{ .Values.search.name }}
    tier: backend
  ports:
    - name: 'search'
      port: 7700
      targetPort: 7700
      protocol: TCP