apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.search.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.search.storageClassName }}
