name: 'Build Docker Image'
description: 'Build a Docker image for the given context'
inputs:
  docker-username:
    description: 'Docker username'
    required: true
  docker-password:
    description: 'Docker password'
    required: true
  image:
    description: 'Image to build'
    required: true
  tags:
    description: 'List of image:tag'
    required: true
  build-args:
    description: 'Build arguments for Docker'
    required: true
  context:
    description: 'Build context for docker'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        load: true
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tags }}
        cache-from: type=registry,ref=${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
