apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nawhas-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - api.k8s.nawhas.com
      secretName: nawhas-tls
  rules:
    - host: api.k8s.nawhas.com
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 80
