apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments.yml
  - services.yml
  - ingress.yml
  - certs/api.yml
secretGenerator:
  - name: api.env
    envs:
      - secrets/api.env
  - name: cloudsql
    files:
      - secrets/cloudsql/credentials.json
