#!/usr/bin/env sh

set -e

DUMP=/opt/dump.sql
echo "Dumping database from staging to $DUMP.";

pg_dump \
  --no-password \
  --no-privileges \
  --clean \
  --if-exists \
  --no-acl \
  --no-owner \
  --schema=public \
  --table reciters \
  --table albums \
  --table tracks \
  --table lyrics \
  --table media \
  --table track_media \
  --table reciter_visits \
  --table track_visits \
  -f "$DUMP" \
  -Fc \
  "$STG_DB_CONNECTION";

echo "Restoring database from $DUMP.";

PGPASSWORD="$POSTGRES_PASSWORD" pg_restore \
  --no-privileges \
  --clean \
  --if-exists \
  --no-acl \
  --no-owner \
  --disable-triggers \
  -U "$POSTGRES_USER" \
  --schema=public \
  -d "$POSTGRES_DB" \
  "$DUMP";

echo "Done!";
