name: 'Build Web Image'
description: 'Build a Docker image for the given context'
inputs:
  docker-username:
    description: 'Docker username'
    required: true
  docker-password:
    description: 'Docker password'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '13.x'
        cache: yarn
        cache-dependency-path: nuxt/yarn.lock

    - name: Install Dependencies
      shell: bash
      working-directory: ./nuxt
      run: yarn install --frozen-lockfile

    - name: Lint Codebase
      shell: bash
      working-directory: ./nuxt
      run: NODE_ENV=production yarn lint --no-fix --format stylish

    - name: Prepare Environment Variables
      id: environment
      shell: bash
      run: |
        version="dev-${SHA::8}"
        echo "::set-output name=version::${version}"
        echo "Version: ${version}"
      env:
        SHA: ${{ github.sha }}
        EVENT_PATH: ${{ github.event_path }}

    - name: Build Image
      uses: ./.github/actions/docker-build-and-push
      with:
        docker-username: ${{ inputs.docker-username }}
        docker-password: ${{ inputs.docker-password }}
        build-args: |
          APP_VERSION=${{ steps.environment.outputs.version }}
        context: ./nuxt
        image: nawhas/web
        tags: nawhas/web:${{ steps.environment.outputs.version }}
