apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - secretRef:
                name: api.env
          volumeMounts:
            - name: secrets
              mountPath: "/var/www/api/storage/secrets"
              readOnly: true
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-nawhas-bravo
      volumes:
        - name: secrets
          secret:
            secretName: api-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  template:
    spec:
      containers:
        - name: queue
          envFrom:
            - secretRef:
                name: api.env
          volumeMounts:
            - name: secrets
              mountPath: "/var/www/api/storage/secrets"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: api-secrets
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-nawhas-bravo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          envFrom:
            - secretRef:
                name: web.env
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-nawhas-bravo
