apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployments.yml
  - ingress.yml
commonLabels:
  env: production
secretGenerator:
  - name: api.env
    envs:
      - api.env
