apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployments.yml
  - ingress.yml
commonLabels:
  env: production
secretGenerator:
  - name: api.env
    envs:
      - secrets/api.env
  - name: web.env
    envs:
      - secrets/web.env
  - name: api-secrets
    files:
      - secrets/github.pem
