apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_MULTIPLE_DATABASES: nawhas,nawhas_events,nawhas_data
  POSTGRES_USER: nawhas
  POSTGRES_PASSWORD: secret
  PGDATA: /var/lib/postgresql/data/pgdata
