apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - secretRef:
                name: api.integration.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  template:
    spec:
      containers:
        - name: queue
          envFrom:
            - secretRef:
                name: api.integration.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          envFrom:
            - secretRef:
                name: web.integration.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          envFrom:
            - secretRef:
                name: search.integration.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  labels:
    app: mail
spec:
  selector:
    matchLabels:
      app: mail
  replicas: 1
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
        - name: mail
          image: mailhog/mailhog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8025
              name: ui
            - containerPort: 1025
              name: smtp
