apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nawhas-ingress
spec:
  tls:
    - hosts:
      - api.dark-mode.intg.k8s.nawhas.com
      - dark-mode.intg.k8s.nawhas.com
      secretName: nawhas-tls
  rules:
    - host: api.dark-mode.intg.k8s.nawhas.com
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 80
    - host: dark-mode.intg.k8s.nawhas.com
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 80
