apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nawhas-ingress
spec:
  tls:
    - hosts:
      - API_DOMAIN
      - APP_DOMAIN
      secretName: nawhas-tls
  rules:
    - host: API_DOMAIN
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 80
    - host: APP_DOMAIN
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 80
