apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nawhas-ingress
spec:
  tls:
    - hosts:
      - ING_API_DOMAIN
      - ING_APP_DOMAIN
      - ING_SEARCH_HOST
      secretName: nawhas-tls
  rules:
    - host: ING_API_DOMAIN
      http:
        paths:
          - backend:
              serviceName: api-nginx
              servicePort: 80
    - host: ING_APP_DOMAIN
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 3000
          - path: /mail
            backend:
              serviceName: mail
              servicePort: 8025
    - host: ING_SEARCH_HOST
      http:
        paths:
          - backend:
              serviceName: search
              servicePort: 7700
