apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nawhas-ingress
spec:
  tls:
    - hosts:
      - <INTG_API_DOMAIN>
      - <INTG_APP_DOMAIN>
      - <INTG_SEARCH_HOST>
      - <INTG_MAIL_HOST>
      secretName: nawhas-tls
  rules:
    - host: <INTG_API_DOMAIN>
      http:
        paths:
          - backend:
              serviceName: api-nginx
              servicePort: 80
    - host: <INTG_APP_DOMAIN>
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 3000
    - host: <INTG_SEARCH_HOST>
      http:
        paths:
          - backend:
              serviceName: search
              servicePort: 7700
    - host: <INTG_MAIL_HOST>
      http:
        paths:
          - backend:
              serviceName: mail
              servicePort: 8025
