apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./postgres/config.yml
  - ./postgres/postgres.yml
  - ./postgres/volume.yml
  - ./mailhog.yml
patchesStrategicMerge:
  - deployments.yml
  - ingress.yml
commonLabels:
  env: integration
namespace: intg-
secretGenerator:
  - name: api.env
    envs:
      - env/api.env
      - env/api.secret.env
  - name: web.env
    envs:
      - env/web.env
      - env/web.secret.env
  - name: search.env
    envs:
      - env/search.secret.env
