kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: api
    tier: backend
  ports:
    - name: 'php'
      port: 9000
      protocol: TCP
    - name: 'nginx'
      port: 80
      targetPort: 8080
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    app: web
    tier: frontend
  ports:
    - name: 'nginx'
      port: 80
      targetPort: 80
      protocol: TCP
