kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: api
    tier: backend
  ports:
    - name: 'php'
      port: 9000
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: api-nginx
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: api-nginx
    tier: backend
  ports:
    - name: 'nginx'
      port: 80
      targetPort: 80
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    app: web
    tier: frontend
  ports:
    - name: 'nuxt'
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
