apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-volume-v1.3.2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
