apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-volume-v0.24.0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
