name: Build Web Image

on: [pull_request]

jobs:
  lint:
    name: Lint Web App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nuxt
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '13.x'
          cache: yarn
          cache-dependency-path: nuxt/yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Codebase
        run: NODE_ENV=production yarn lint --no-fix --format stylish

  build:
    name: Build Web Image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Environment Variables
        id: environment
        run: |
          version="dev-${SHA::8}"
          echo "::set-output name=version::dev-${version}"
        env:
          SHA: ${{ github.sha }}
          EVENT_PATH: ${{ github.event_path }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nuxt
          push: true
          build-args: |
            APP_VERSION=${{ steps.environment.outputs.version }}
          tags: nawhas/web:${{ steps.environment.outputs.version }}
          cache-from: type=registry,ref=nawhas/web:buildcache
          cache-to: type=registry,ref=nawhas/web:buildcache,mode=max
