name: Build Web Image

on: [pull_request]

jobs:
  lint:
    name: Lint Web App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nuxt
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '13.x'
          cache: yarn
          cache-dependency-path: nuxt/yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Codebase
        run: NODE_ENV=production yarn lint --no-fix --format stylish
  build:
    name: Build Web Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Environment Variables
        id: environment
        run: |
          version="dev-${SHA::8}"
          echo "::set-output name=version::${version}"
          echo "Version: ${version}"
        env:
          SHA: ${{ github.sha }}
          EVENT_PATH: ${{ github.event_path }}

      - name: Build Image
        uses: ./.github/actions/docker-build-and-push
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          build-args: |
            APP_VERSION=${{ steps.environment.outputs.version }}
          context: ./nuxt
          image: nawhas/web
          tags: nawhas/web:${{ steps.environment.outputs.version }}
