name: Deploy Nawhas.com to K8S

on:
  push:
    branches:
      - digital-ocean-k8s

env:
  API_IMAGE: nawhas/api

jobs:
  build:
    name: Build & Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-nawhas > $GITHUB_WORKSPACE/.kubeconfig

      - name: Docker Login
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build
        run: |
          docker build --file ./api/Dockerfile \
            -t $API_IMAGE:${GITHUB_SHA::8} \
            -t $API_IMAGE:${GITHUB_REF##*/} \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="${GITHUB_REF##*/}" \
            ./api

      - name: Publish
        run: |
          docker push $API_IMAGE:${GITHUB_SHA::8}
          docker push $API_IMAGE:${GITHUB_REF##*/}

      # Set up kustomize
      - name: Set up Kustomize
        working-directory: ./k8s
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Update secrets.
      - name: Update secrets
        working-directory: ./k8s/secrets
        run: |
          ./decrypt.sh
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        working-directory: ./k8s
        run: |
          ./kustomize edit set image gcr.io/GKE_PROJECT/IMAGE:TAG=$API_IMAGE:${GITHUB_SHA::8}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/api-deployment
          kubectl get services -o wide
