name: Deploy Integration Environment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR number
        id: pr_number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
        env:
          PR_NUMBER: ${{ steps.pr_number.outputs.pr_number }}

      - name: Deploy through ArgoCD
        if: contains(github.head_ref, '-integration')
        uses: ./.github/actions/argocd-deploy
        with:
          server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          pr_number: ${{ github.event.pull_request.number }}
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          environment: integration
          secret-key: ${{ secrets.GPG_KEY }}
#          namespace: ${{ env.NAMESPACE }}
#          tag: ${{ env.APP_VERSION }}

