name: Deploy Integration Environment

on:
  pull_request:
    branches:
      - '*-integration'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR number
        id: pr_number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
        env:
          PR_NUMBER: ${{ steps.pr_number.outputs.pr_number }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
