name: Clean Up Integration Build

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  clean:
    name: Clean Up Integration Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 783417
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR number
        id: pr_number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
        env:
          PR_NUMBER: ${{ steps.pr_number.outputs.pr_number }}
      
      - uses: ./.github/actions/argocd-deploy-cleanup
        if: contains(github.head_ref, '-integration')
        with:
          server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          argocd-app-name: nawhas-integration-${{ github.event.pull_request.number }}
