name: Pull Request Build

on: [pull_request]

concurrency:
  group: integration
  cancel-in-progress: true

jobs:
  # Notify Build Started
  notify_start:
    name: Notify Build Started
    runs-on: ubuntu-latest
    if: endsWith(github.head_ref, '-integration')
    steps:
      - name: Notify Build Started
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: deploys
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # Setup Job
  setup:
    name: Setup Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine PR Number
        id: environment
        run: |
          pr_num="$EVENT_NUMBER"
          short_sha="${SHA::8}"
          echo "::set-output name=pr_num::${pr_num}"
          echo "::set-output name=short_sha::${short_sha}"
        env:
          EVENT_NUMBER: ${{github.event.number}}
          SHA: ${{ github.sha }}
    outputs:
      pr_num: ${{ steps.environment.outputs.pr_num }}
      short_sha: ${{ steps.environment.outputs.short_sha }}
  # Build API Image
  build_api:
    name: Build API Image
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/api-build
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          extra-tags: |
            nawhas/api:pr-${{ needs.setup.outputs.pr_num }}
            nawhas/api:pr-${{ needs.setup.outputs.pr_num }}-${{ needs.setup.outputs.short_sha }}
  # Lint Web App
  lint_web:
    name: Lint Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: ./.github/actions/web-lint
  # Build Web Image
  build_web:
    name: Build Web Image
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/web-build
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          extra-tags: |
            nawhas/web:pr-${{ needs.setup.outputs.pr_num }}
            nawhas/web:pr-${{ needs.setup.outputs.pr_num }}-${{ needs.setup.outputs.short_sha }}
  test_api:
    name: Test API Image
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Test API Image
        uses: ./.github/actions/api-build-test

      - name: Prepare .env.ci
        run: |
          cp api/.env.ci.example api/.env.ci

      - name: Pull Services
        run: |
          ./dev --ci pull db cache search
        env:
          API_IMAGE_TAG: test
          # API_TEST_IMAGE_TAG: test
          # WEB_IMAGE_TAG: dev-${{ needs.setup.outputs.short_sha }}

      - name: Run PHPStan
        shell: bash
        run: |
          docker run --rm nawhas/api:test ./ci/phpstan.sh

      - name: Run Unit Tests
        shell: bash
        run: |
          docker run --rm nawhas/api:test ./vendor/bin/phpunit --testsuite Unit

      - name: Run Feature Tests
        run: |
          ./dev --ci up -d api test_db search
          ./dev --ci art wait:database
          ./dev --ci art search:setup --reset
          ./dev --ci test:feature
        env:
          API_IMAGE_TAG: test
  dusk:
    name: Run Dusk Tests
    runs-on: ubuntu-latest
    needs: [setup, build_api, build_web]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Test API Image
        uses: ./.github/actions/api-build-test

      - name: Prepare .env.ci
        run: |
          cp api/.env.ci.example api/.env.ci

      - name: Pull Services
        run: |
          ./dev --ci pull -q api web nginx mail selenium db search cache
        env:
          API_IMAGE_TAG: dev-${{ needs.setup.outputs.short_sha }}
          WEB_IMAGE_TAG: dev-${{ needs.setup.outputs.short_sha }}
          API_TEST_IMAGE_TAG: test

      - name: Run Dusk Tests
        run: |
          ./dev --ci dusk
        env:
          API_IMAGE_TAG: dev-${{ needs.setup.outputs.short_sha }}
          WEB_IMAGE_TAG: dev-${{ needs.setup.outputs.short_sha }}
          API_TEST_IMAGE_TAG: test

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: api/tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: api/tests/Browser/console
  ################################################################
  # Deploy Integration Environment
  ################################################################
  deploy:
    name: Deploy Integration Environment
    runs-on: ubuntu-latest
    needs: [lint_web, build_web, build_api, test_api]
    if: endsWith(github.head_ref, '-integration')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: |
          ./scripts/github/prepare-integration-environment.sh

      - name: Substitute Deployment Variables
        run: |
          {
            echo "APP_DOMAIN=${APP_DOMAIN}"
            echo "ALGOLIA_PREFIX=${ALGOLIA_PREFIX}"
            echo "SESSION_COOKIE_PREFIX=${SESSION_COOKIE_PREFIX}"
          } >> ./k8s/overlays/integration/env/api.env
          
          {
            echo "API_BASE_URL=https://${API_DOMAIN}/"
            echo "APP_DOMAIN=https://${APP_DOMAIN}"
            echo "SEARCH_HOST=https://${SEARCH_HOST}"
          } >> ./k8s/overlays/integration/env/web.env
          
          cat ./k8s/overlays/integration/ingress.yml \
            | sed "s/<INTG_APP_DOMAIN>/${APP_DOMAIN}/g" \
            | sed "s/<INTG_API_DOMAIN>/${API_DOMAIN}/g" \
            | sed "s/<INTG_SEARCH_HOST>/${SEARCH_HOST}/g" \
            | sed "s/<INTG_MAIL_HOST>/${MAIL_HOST}/g" \
          > ./k8s/overlays/integration/ingress.yml

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          environment: integration
          secret-key: ${{ secrets.GPG_KEY }}
          namespace: ${{ env.NAMESPACE }}
          tag: ${{ env.APP_VERSION }}

      - name: Post Link on PR
        if: success()
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Your integration branch has been deployed to https://${{ env.APP_DOMAIN }}"
          check_for_duplicate_msg: true
  ################################################################
  # Notify Build Status
  ################################################################
  notify_failure:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build_api, build_web, deploy]
    if: endsWith(github.head_ref, '-integration')
    steps:
      - name: Notify Build Success
        uses: voxmedia/github-action-slack-notify-build@v1
        if: needs.build_api.result == 'success' && needs.build_web.result == 'success' && needs.deploy.result == 'success'
        with:
          channel: deploys
          status: SUCCESS
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify Build Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        if: needs.build_api.result == 'failure' || needs.build_web.result == 'failure' || needs.deploy.result == 'failure'
        with:
          channel: deploys
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
