name: Clean Up Integration Build

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  clean:
    name: Clean Up Integration Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 783417
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@v1.7.0
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-nawhas > $GITHUB_WORKSPACE/.kubeconfig

      - name: Prepare Environment
        run: |
          ./scripts/github/prepare-integration-environment.sh

      - name: Delete Namespace
        working-directory: ./k8s/overlays/integration
        run: |
          if [[ $(kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig get namespace | grep "$NAMESPACE") != "" ]]; then
            kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig delete namespace "$NAMESPACE"
          fi
