name: Deploy Integration Environment

on:
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR number
        id: pr_number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
        env:
          PR_NUMBER: ${{ steps.pr_number.outputs.pr_number }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.6.7
          command: login
          options: ${{ secrets.ARGOCD_SERVER }} --grpc-web --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}
        
      - uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.6.7
          command: account
          options: list