name: 'Integration ArgoCD Cleanup'

on:
  pull_request:
    types: [closed]
    branches:
      - '*-integration'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/argocd-deploy-cleanup
        with:
          server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          argocd-app-name: nawhas-integration-${{ github.event.pull_request.head_ref }}

