name: Deploy Nawhas.com to GKE

on:
  push:
    branches:
      - k8s

env:
  IMAGE: api
  GKE_PROJECT: nawhas
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker
      # Build the Docker image
      - name: Build
        run: |
          docker build --file ./api/Dockerfile \
            -t gcr.io/$GKE_PROJECT/$IMAGE:${GITHUB_SHA::8} \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="${GITHUB_REF##*/}" \
            ./api
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/$GKE_PROJECT/$IMAGE:${GITHUB_SHA::8}
          docker push gcr.io/$GKE_PROJECT/$IMAGE:${GITHUB_REF##*/}
      # Set up kustomize
      - name: Set up Kustomize
        working-directory: ./k8s
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        working-directory: ./k8s
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone $GKE_ZONE --project $GKE_PROJECT
          ./kustomize edit set image gcr.io/GKE_PROJECT/IMAGE:TAG=gcr.io/$GKE_PROJECT/$IMAGE:${GITHUB_SHA::8}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/api-deployment
          kubectl get services -o wide
