name: Production Deploy

on:
  release:
    types: [published]

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  # Notify Build Started
  notify_start:
    name: Notify Build Started
    runs-on: ubuntu-latest
    steps:
      - name: Notify Build Started
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: deploys
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # Setup Job
  setup:
    name: Setup Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Meta
        id: meta
        run: |
          tag="${REF##*/}"
          echo "::set-output name=tag::${tag}"
        env:
          REF: ${{ github.ref }}
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
  # Build API Image
  build_api:
    name: Build Production API Image
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/api-build
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          extra-tags: |
            nawhas/api:latest
            nawhas/api:${{ needs.setup.outputs.tag }}
  build_web:
    name: Build Web Image for Production
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/web-build
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          extra-tags: |
            nawhas/web:latest
            nawhas/web:${{ needs.setup.outputs.tag }}
  # Deploy Production Environment
  deploy:
    name: Deploy Production Environment
    runs-on: ubuntu-latest
    needs: [build_api, build_web]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@v1.7.0
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-nawhas > $GITHUB_WORKSPACE/.kubeconfig

      - name: Decrypt secrets
        working-directory: ./k8s/overlays/production/secrets
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output api.env api.env.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output web.env web.env.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output search.env search.env.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output github.pem github.pem.gpg
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      # Set up kustomize
      - name: Set up Kustomize
        working-directory: ./k8s/overlays/production
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        working-directory: ./k8s/overlays/production
        run: |
          ./kustomize edit set image IMAGE:TAG=$API_IMAGE:${GITHUB_REF##*/}
          ./kustomize edit set image WEB:TAG=$WEB_IMAGE:${GITHUB_REF##*/}
          ./kustomize build . | kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f -
          kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout status --timeout=3m deployment/api
          kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout status --timeout=3m deployment/web
          kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig get services -o wide
  # Notify Build Status
  notify_failure:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build_api, build_web, deploy]
    if: always()
    steps:
      - name: Notify Build Success
        uses: voxmedia/github-action-slack-notify-build@v1
        if: needs.build_api.result == 'success' && needs.build_web.result == 'success' && needs.deploy.result == 'success'
        with:
          channel: deploys
          status: SUCCESS
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify Build Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        if: needs.build_api.result == 'failure' || needs.build_web.result == 'failure' || needs.deploy.result == 'failure'
        with:
          channel: deploys
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
