name: Build & Test Vue App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Build Web Container'
      run: docker build ./web --file ./web/Dockerfile --tag nawhas/web:${GITHUB_SHA::8} --tag nawhas/web:${GITHUB_REF##*/}
