name: Build & Test Vue App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: 'Install Dependencies'
    - run: yarn install --frozen-lockfile
      working-directory: ./web

    - name: 'Build App'
    - run: yarn build
      working-directory: ./web
      env:
        CI: true
