name: Build & Test Vue App

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - run: yarn install --frozen-lockfile
        working-directory: ./web

      - name: 'Lint JS'
        run: yarn lint --no-fix
        working-directory: ./web
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Build Web Container'
      run: docker build ./web --file ./web/Dockerfile --tag nawhas/web:${GITHUB_SHA::8} --tag nawhas/web:${GITHUB_REF##*/}
