name: Build Web Image

on: [pull_request]

jobs:
  ################################################################
  # Build Web Image
  ################################################################
  build_web:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Environment
        run: |
          ./scripts/github/prepare-integration-environment.sh

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nuxt
          push: true
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          tags: nawhas/web:${{ env.APP_VERSION }}
          cache-from: type=registry,ref=nawhas/web:latest
          cache-to: type=inline
