apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - secretRef:
                name: api.staging.env
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-nawhas-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  template:
    spec:
      containers:
        - name: queue
          envFrom:
            - secretRef:
                name: api.staging.env
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-nawhas-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          envFrom:
            - secretRef:
                name: web.staging.env
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-nawhas-dev
