apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - secretRef:
                name: api.env
      initContainers:
        - name: init-boot
          envFrom:
            - secretRef:
                name: api.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  template:
    spec:
      containers:
        - name: queue
          envFrom:
            - secretRef:
                name: api.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          envFrom:
            - secretRef:
                name: web.env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          envFrom:
            - secretRef:
                name: search.env
