apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nawhas-ingress
spec:
  tls:
    - hosts:
      - api.staging.nawhas.com
      - staging.nawhas.com
      - search.staging.nawhas.com
      secretName: nawhas-tls
  rules:
    - host: api.staging.nawhas.com
      http:
        paths:
          - backend:
              serviceName: api-nginx
              servicePort: 80
    - host: staging.nawhas.com
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 3000
    - host: search.staging.nawhas.com
      http:
        paths:
          - backend:
              serviceName: search
              servicePort: 7700
