apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployments.yml
  - ingress.yml
commonLabels:
  env: staging
namespace: stg
secretGenerator:
  - name: api.staging.env
    envs:
      - secrets/api.staging.env
  - name: web.staging.env
    envs:
      - secrets/web.staging.env
  - name: search.staging.env
    envs:
      - secrets/search.staging.env
