apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployments.yml
  - ingress.yml
commonLabels:
  env: staging
namespace: stg
secretGenerator:
  - name: api.env
    envs:
      - env/api.env
      - env/api.secret.env
  - name: web.env
    envs:
      - env/web.env
      - env/web.secret.env
  - name: search.env
    envs:
      - env/search.secret.env
